spring:
  data:
    rest:
      base-path: "api"
    mongodb:
      uri: "@mongodb.uri@"

server:
  port: 8080
  
logging:
  level:
    org.springframework: "off"
    
uolia:
  cw:
    queries:
      cw1:
        a: "$.ecc.a"
        b: "$.ecc.b"
        k: "$.ecc.k"
        order: "$.ecc.order"
        px: "$.assignment.modk-add.p.x"
        py: "$.assignment.modk-add.p.y"
        qx: "$.assignment.modk-add.q.x"
        qy: "$.assignment.modk-add.q.y"
        rx: "$.assignment.modk-add.r.x"
        ry: "$.assignment.modk-add.r.y"
        sx: "$.assignment.modk-mul.s.x"
        sy: "$.assignment.modk-mul.s.y"
      cw2:
        a: "$.ecc.a"
        b: "$.ecc.b"
        k: "$.ecc.k"
        gx: "$.ecc.g.x"
        gy: "$.ecc.g.y"
        order: "$.ecc.order"
        da: "$.assignment.key_exchange.alice.da"
        qax: "$.assignment.key_exchange.alice.qa.x"
        qay: "$.assignment.key_exchange.alice.qa.y"
        db: "$.assignment.key_exchange.bob.db"
        qbx: "$.assignment.key_exchange.bob.qb.x"
        qby: "$.assignment.key_exchange.bob.qb.y"
        keyx: "$.assignment.key_exchange.key.x"
        keyy: "$.assignment.key_exchange.key.y"
  
---
spring:
  profiles: test
  data:
    mongodb:
      uri: "mongodb://127.0.0.1:37017/ecc"
         
